import type { EngineBoard, EngineSkill, EngineType } from "./vocab";
import type { BlueprintSectionDefaults, DifficultyMix, SectionFilter } from "./blueprint-schema";

/* ------------------------------------------------------------------- rng */

/**
 * Deterministic PRNG (mulberry32). Every generated test records its seed, so a
 * test can be regenerated byte-for-byte for debugging or for an appeal, and two
 * users taking the "daily" quiz get the same paper on the same date.
 */
export function createRng(seed: number): () => number {
  let a = seed >>> 0;
  return function next() {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Stable 32-bit hash so a string (e.g. "daily:2026-09-25") becomes a seed. */
export function hashSeed(input: string): number {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h >>> 0;
}

/** Fisher-Yates using the supplied rng. Returns a new array. */
export function seededShuffle<T>(items: readonly T[], rng: () => number): T[] {
  const out = items.slice();
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    const tmp = out[i];
    out[i] = out[j];
    out[j] = tmp;
  }
  return out;
}

/* ------------------------------------------------------------- pool shape */

/** Minimal question shape the generator needs; the DB select is a superset. */
export type PoolQuestion = {
  id: string;
  engine_type: string | null;
  topic_id: string | null;
  subtopic_id: string | null;
  parent_id: string | null;
  difficulty: number | null;
  skill: string | null;
  board_pattern: string | null;
  pyq_year: number | null;
  lang: string | null;
  est_time_sec: number | null;
};

export type PickedQuestion = {
  questionId: string;
  sectionId: string | null;
  position: number;
  difficulty: number | null;
};

export type GenerationWarning = {
  sectionId: string | null;
  code:
    | "SHORTFALL"
    | "RELAXED_DIFFICULTY"
    | "RELAXED_TYPE"
    | "RELAXED_TOPIC"
    | "RELAXED_SKILL"
    | "RELAXED_TAG"
    | "RELAXED_PYQ"
    | "RELAXED_RECENT"
    | "ADAPTIVE_SHORTFALL";
  message: string;
  requested: number;
  filled: number;
};

export type GeneratorContext = {
  /** Question ids to avoid, most-recent first (already-seen exclusion). */
  recentlySeen?: readonly string[];
  /** topic_id -> mastery 0..1 (1 = mastered). Used by weak-area / diagnostic. */
  topicMastery?: Readonly<Record<string, number>>;
  /** Suppresses the recently-seen exclusion when the bank is too small. */
  allowRepeat?: boolean;
};

/* -------------------------------------------------------------- matching */

function intersects(a: readonly string[], b: readonly string[]): boolean {
  if (a.length === 0) return true;
  const set = new Set(b);
  return a.some((v) => set.has(v));
}

/**
 * A single relaxation step. Each level drops exactly one constraint, and the
 * order is fixed and documented so a shortfall is always resolved the same way
 * for a given input: the least pedagogically important constraint goes first
 * (recency, then PYQ-only, then difficulty band, then tags, then skill, then
 * type, and only last the topic scope).
 */
export const RELAXATION_ORDER = [
  "recent",
  "pyq",
  "board",
  "difficulty",
  "tags",
  "skill",
  "type",
  "topic",
] as const;

export type RelaxationLevel = (typeof RELAXATION_ORDER)[number];

/** How far a filter has been relaxed; `0` means "apply the filter exactly". */
export type Relaxation = Set<RelaxationLevel>;

/**
 * Does `q` satisfy the filter at the given relaxation level?
 * Constraints in `relaxed` are ignored entirely.
 */
export function matchesFilter(
  q: PoolQuestion,
  filter: SectionFilter,
  relaxed: Relaxation = new Set()
): boolean {
  if ((q.lang ?? "en") !== filter.lang) return false;

  // A case-based *parent* is the passage row itself: it carries the shared
  // stem, scores zero marks and must never be served as a standalone question.
  // It is identified by being case_based with no parent_id - a plain standalone
  // question of any other type is NOT a parent and must stay eligible, which is
  // why this cannot simply test `!q.parent_id`.
  const isCaseParent = q.engine_type === "case_based" && !q.parent_id;
  if (isCaseParent && !relaxed.has("topic") && filter.exclude_parents) return false;
  if (q.parent_id && !relaxed.has("topic") && filter.exclude_children) return false;

  if (!relaxed.has("topic")) {
    if (filter.topic_ids.length > 0 && (!q.topic_id || !filter.topic_ids.includes(q.topic_id))) return false;
    if (
      filter.subtopic_ids.length > 0 &&
      (!q.subtopic_id || !filter.subtopic_ids.includes(q.subtopic_id))
    ) {
      return false;
    }
  }

  if (!relaxed.has("type")) {
    if (filter.types.length > 0 && (!q.engine_type || !filter.types.includes(q.engine_type as EngineType))) {
      return false;
    }
  }

  if (!relaxed.has("difficulty")) {
    const d = q.difficulty ?? 2;
    if (d < filter.difficulty_min || d > filter.difficulty_max) return false;
  }

  if (!relaxed.has("skill")) {
    if (filter.skills.length > 0 && (!q.skill || !filter.skills.includes(q.skill as EngineSkill))) return false;
  }

  if (!relaxed.has("board")) {
    if (
      filter.board_patterns.length > 0 &&
      (!q.board_pattern || !filter.board_patterns.includes(q.board_pattern as EngineBoard))
    ) {
      return false;
    }
  }

  if (filter.pyq_only && !relaxed.has("pyq")) {
    if (!q.pyq_year) return false;
  }

  return true;
}

/** Tag membership is checked separately because tags live in a side table. */
export function matchesTags(qTags: readonly string[], filter: SectionFilter, relaxed: Relaxation = new Set()): boolean {
  if (relaxed.has("tags") || filter.tags.length === 0) return true;
  return intersects(filter.tags, qTags);
}


/* ------------------------------------------------------- difficulty mix */

/**
 * Expands a requested difficulty mix into per-band quotas that sum to `count`.
 * An empty mix is expressed as a single sentinel band 0 meaning "no preference",
 * so the caller treats both cases uniformly.
 */
export function expandDifficultyMix(mix: DifficultyMix, count: number): Array<[number, number]> {
  if (count <= 0) return [];
  const bands = Object.entries(mix)
    .map(([k, v]) => [Number(k), v] as [number, number])
    .filter(([, v]) => v > 0)
    .sort((a, b) => a[0] - b[0]);

  if (bands.length === 0) return [[0, count]];

  const total = bands.reduce((s, [, v]) => s + v, 0);
  // Scale requested weights onto the requested count, then hand the remainder
  // out in band order so the quotas always total `count` exactly.
  const quotas = bands.map(
    ([band, weight]) => [band, Math.floor((weight / total) * count)] as [number, number]
  );
  let assigned = quotas.reduce((s, [, v]) => s + v, 0);
  let i = 0;
  while (assigned < count) {
    quotas[i % quotas.length][1] += 1;
    assigned += 1;
    i += 1;
  }
  return quotas;
}

/* ----------------------------------------------------- section filling */

export type Candidate = { question: PoolQuestion; tags: readonly string[] };

export type FillResult = {
  picked: Candidate[];
  warnings: GenerationWarning[];
  usedRelaxations: RelaxationLevel[];
};

function eligibleAt(
  pool: readonly Candidate[],
  filter: SectionFilter,
  relaxed: Relaxation,
  recentSet: ReadonlySet<string>,
  ctx: GeneratorContext
): Candidate[] {
  return pool.filter((c) => {
    if (!matchesFilter(c.question, filter, relaxed)) return false;
    if (!matchesTags(c.tags, filter, relaxed)) return false;
    if (!relaxed.has("recent") && !ctx.allowRepeat && recentSet.has(c.question.id)) return false;
    return true;
  });
}

/**
 * Fills one section. Tries the filter exactly first, then walks RELAXATION_ORDER
 * one step at a time until the count is met or the constraints are exhausted.
 * Every shortfall produces a warning naming the section and the level that had
 * to be dropped, so an under-filled blueprint is visible to the admin rather
 * than silently short.
 */
export function fillSection(
  pool: readonly Candidate[],
  section: BlueprintSectionDefaults & { id?: string | null },
  rng: () => number,
  ctx: GeneratorContext = {}
): FillResult {
  const warnings: GenerationWarning[] = [];
  const usedRelaxations: RelaxationLevel[] = [];
  const recentSet = new Set(ctx.recentlySeen ?? []);
  const chosen: Candidate[] = [];
  const chosenIds = new Set<string>();

  const take = (candidates: readonly Candidate[], quota: number): number => {
    if (quota <= 0) return 0;
    let added = 0;
    for (const c of seededShuffle(candidates, rng)) {
      if (added >= quota) break;
      if (chosenIds.has(c.question.id)) continue;
      chosenIds.add(c.question.id);
      chosen.push(c);
      added += 1;
    }
    return added;
  };

  const quotas = expandDifficultyMix(section.difficulty_mix, section.count);
  const hasMix = !(quotas.length === 1 && quotas[0][0] === 0);

  const attempt = (relaxed: Relaxation): number => {
    const eligible = eligibleAt(pool, section.filter, relaxed, recentSet, ctx);
    if (!hasMix) return take(eligible, section.count - chosen.length);

    // Honour the requested difficulty mix band by band. When the band itself has
    // been relaxed there is no band to key on, so fall back to a plain slice.
    if (relaxed.has("difficulty")) return take(eligible, section.count - chosen.length);

    for (const [band, quota] of quotas) {
      if (quota <= 0) continue;
      const remaining = section.count - chosen.length;
      if (remaining <= 0) break;
      const bandPool = eligible.filter((c) => (c.question.difficulty ?? 2) === band);
      take(bandPool, Math.min(quota, remaining));
    }
    return chosen.length;
  };

  const relaxed: Relaxation = new Set();
  attempt(relaxed);

  for (const level of RELAXATION_ORDER) {
    if (chosen.length >= section.count) break;

    // Recency is the constraint to give up last. A short paper that never repeats
    // a question the student just sat is better than a full one that does, so
    // "recent" is only relaxed when nothing unseen is left at all - otherwise the
    // section stays short and reports a SHORTFALL.
    if (level === "recent" && !relaxed.has("recent") && !ctx.allowRepeat) {
      const withoutRecency = new Set(relaxed);
      withoutRecency.delete("recent");
      if (eligibleAt(pool, section.filter, withoutRecency, recentSet, ctx).length > 0) continue;
    }

    const before = chosen.length;
    relaxed.add(level);
    usedRelaxations.push(level);
    attempt(relaxed);
    if (chosen.length > before && chosen.length < section.count) {
      warnings.push({
        sectionId: section.id ?? null,
        code: `RELAXED_${level.toUpperCase()}` as GenerationWarning["code"],
        message: `Relaxed "${level}" to fill section "${section.title}".`,
        requested: section.count,
        filled: chosen.length,
      });
    }
  }

  if (chosen.length < section.count) {
    warnings.push({
      sectionId: section.id ?? null,
      code: "SHORTFALL",
      message: `Section "${section.title}" wanted ${section.count} questions but only ${chosen.length} are available in the bank.`,
      requested: section.count,
      filled: chosen.length,
    });
  }

  return { picked: chosen, warnings, usedRelaxations };
}

/* ------------------------------------------------------------- assembly */

export type ResolvedSection = BlueprintSectionDefaults & { id?: string | null };

export type GenerationResult = {
  picks: PickedQuestion[];
  warnings: GenerationWarning[];
  seed: number;
  usedRelaxations: RelaxationLevel[];
};

/**
 * Assembles a full test from already-resolved sections. Section order is
 * respected and, when `shuffleQuestions` is set, the sections' contents are
 * shuffled within the section but sections keep their declared order, so a
 * blueprint that groups "Section A then Section B" still reads that way.
 * Questions are never reused across sections.
 */
function assemble(
  sections: readonly ResolvedSection[],
  pool: readonly Candidate[],
  seed: number,
  rng: () => number,
  ctx: GeneratorContext,
  shuffleQuestions: boolean
): GenerationResult {
  const warnings: GenerationWarning[] = [];
  const usedRelaxations: RelaxationLevel[] = [];
  const picks: PickedQuestion[] = [];
  const used = new Set<string>();

  for (const section of sections) {
    const remaining = pool.filter((c) => !used.has(c.question.id));
    const result = fillSection(remaining, section, rng, ctx);
    for (const c of result.picked) used.add(c.question.id);
    warnings.push(...result.warnings);
    usedRelaxations.push(...result.usedRelaxations);
    const ordered = shuffleQuestions ? seededShuffle(result.picked, rng) : result.picked;
    for (const c of ordered) {
      picks.push({
        questionId: c.question.id,
        sectionId: section.id ?? null,
        position: picks.length,
        difficulty: c.question.difficulty,
      });
    }
  }

  return { picks, warnings, seed, usedRelaxations: Array.from(new Set(usedRelaxations)) };
}

/** Static mode: filter, seed, fill. The default for topic/chapter/board tests. */
export function generateStatic(
  sections: readonly ResolvedSection[],
  pool: readonly Candidate[],
  seed: number,
  ctx: GeneratorContext = {},
  shuffleQuestions = true
): GenerationResult {
  return assemble(sections, pool, seed, createRng(seed), ctx, shuffleQuestions);
}

/* -------------------------------------------------------------- adaptive */

export type AdaptiveOptions = {
  /** Total questions to serve. */
  total: number;
  /** Minimum band; the walk starts at `startDifficulty`. */
  startDifficulty?: number;
  /** Stop early once this many consecutive correct answers are seen. */
  confidenceThreshold?: number;
};

/**
 * Adaptive mode: start at medium difficulty and step up after a correct answer,
 * down after a wrong one, serving one question at a time. The caller supplies
 * the answer history because grading lives in Phase 5; this function is pure so
 * the stepping logic is unit-testable without a database.
 *
 * Returns the next question to serve, or null when the walk is finished.
 */
export function nextAdaptiveQuestion(
  pool: readonly Candidate[],
  answered: ReadonlyArray<{ questionId: string; correct: boolean }>,
  opts: AdaptiveOptions
): Candidate | null {
  const served = new Set(answered.map((a) => a.questionId));
  if (answered.length >= opts.total) return null;

  const correctStreak = (() => {
    let n = 0;
    for (let i = answered.length - 1; i >= 0 && answered[i].correct; i--) n += 1;
    return n;
  })();
  if (opts.confidenceThreshold && correctStreak >= opts.confidenceThreshold) return null;

  const wrongStreak = (() => {
    let n = 0;
    for (let i = answered.length - 1; i >= 0 && !answered[i].correct; i--) n += 1;
    return n;
  })();

  const base = opts.startDifficulty ?? 2;
  const target = answered.length === 0 ? base : correctStreak >= 2 ? 3 : wrongStreak >= 2 ? 1 : base;

  const unseen = pool.filter((c) => !served.has(c.question.id));
  if (unseen.length === 0) return null;

  const atTarget = unseen.filter((c) => (c.question.difficulty ?? 2) === target);
  const source = atTarget.length > 0 ? atTarget : unseen;
  // Deterministic within a given answer history, so a resumed attempt replays
  // the same walk instead of drifting.
  const seed = hashSeed(answered.map((a) => `${a.questionId}:${a.correct ? 1 : 0}`).join("|") || "adaptive-start");
  return seededShuffle(source, createRng(seed))[0] ?? null;
}

/* ------------------------------------------------------ weak-area / daily */

/**
 * Weights a topic by inverse mastery so a diagnostic or weak-area test spends
 * most of its questions where the student is weakest. Topics with no history
 * are treated as 0 mastery (fully weighted) so a new learner is assessed
 * broadly rather than skipped.
 */
export function weakAreaWeights(
  topicIds: readonly string[],
  mastery: Readonly<Record<string, number>> = {}
): Record<string, number> {
  const weights: Record<string, number> = {};
  for (const id of topicIds) {
    const m = Math.min(1, Math.max(0, mastery[id] ?? 0));
    weights[id] = Math.round((1 - m) * 1000) / 1000;
  }
  return weights;
}

/**
 * Weighted sampling without replacement, using the supplied rng. Weights need
 * not sum to 1; zero-weight topics are never picked.
 */
export function weightedSample<T>(
  items: readonly T[],
  weightOf: (item: T) => number,
  count: number,
  rng: () => number
): T[] {
  const remaining = items.slice();
  const out: T[] = [];
  for (let n = 0; n < count && remaining.length > 0; n++) {
    let total = 0;
    for (const it of remaining) total += Math.max(0, weightOf(it));
    if (total <= 0) break;
    let roll = rng() * total;
    let idx = remaining.length - 1;
    for (let i = 0; i < remaining.length; i++) {
      roll -= Math.max(0, weightOf(remaining[i]));
      if (roll <= 0) {
        idx = i;
        break;
      }
    }
    out.push(remaining[idx]);
    remaining.splice(idx, 1);
  }
  return out;
}

/** Daily mode: deterministic per date, so every student gets the same paper. */
export function dailySeed(dateISO: string, blueprintSlug: string): number {
  return hashSeed(`daily:${dateISO}:${blueprintSlug}`);
}
