// Phase-1 seed data: Q07-Q12 (MCQ continued)
module.exports = [
{ code:'Q07', t:'mcq', topic:'types-of-reactions', sub:'decomposition-reactions', d:2, skill:'application', marks:1, neg:0.25, time:60, board:'CBSE', pyq:2022,
stem:'Green ferrous sulphate crystals heated in a dry boiling tube give: $2\\text{FeSO}_4 \\xrightarrow{\\Delta} \\text{Fe}_2\\text{O}_3 + \\text{SO}_2 + \\text{SO}_3$. The correct observation is:',
opts:[['Blue crystals, oxygen gas released',0],['Reddish-brown solid with smell of burning sulphur',1],['White residue with no gas',0],['Yellow residue with brown fumes',0]],
rub:'Ferric oxide is reddish-brown; sulphur oxides smell.', expl:'Green $\\text{FeSO}_4$ decomposes to reddish-brown $\\text{Fe}_2\\text{O}_3$ plus $\\text{SO}_2$ and $\\text{SO}_3$ gases smelling of burning sulphur.', tags:['thermal-decomposition','ferrous-sulphate'] },
{ code:'Q08', t:'mcq', topic:'exothermic-endothermic', sub:'respiration-combustion', d:1, skill:'recall', marks:1, neg:0.25, time:40, board:'CBSE', pyq:null,
stem:'Which of the following processes is endothermic?',
opts:[['Respiration in cells',0],['Burning of natural gas',0],['Photosynthesis in leaves',1],['Dissolution of quicklime in water',0]],
rub:'Endothermic processes absorb heat from surroundings.', expl:'Photosynthesis $6\\text{CO}_2 + 6\\text{H}_2\\text{O} \\xrightarrow{\\text{sunlight}} \\text{C}_6\\text{H}_{12}\\text{O}_6 + 6\\text{O}_2$ absorbs light energy; the others release heat.', tags:['endothermic','photosynthesis'] },
{ code:'Q09', t:'mcq', topic:'rancidity', sub:'causes-of-rancidity', d:1, skill:'recall', marks:1, neg:0.25, time:40, board:'CBSE', pyq:2020,
stem:'Chips manufacturers flush packets with nitrogen gas in order to:',
opts:[['Add flavour to chips',0],['Prevent oxidation of oils (rancidity)',1],['Increase packet weight',0],['Kill bacteria by heat',0]],
rub:'Nitrogen displaces oxygen, stopping oxidation of fats.', expl:'Nitrogen provides an inert atmosphere so oils in chips are not oxidised; this prevents rancidity and keeps taste and smell intact.', tags:['rancidity','nitrogen-flushing'] },
{ code:'Q10', t:'mcq', topic:'types-of-reactions', sub:'double-displacement', d:2, skill:'application', marks:1, neg:0.25, time:60, board:'SEBA', pyq:2021,
stem:'On mixing sodium sulphate and barium chloride solutions: $\\text{Na}_2\\text{SO}_4 + \\text{BaCl}_2 \\rightarrow \\text{BaSO}_4 + 2\\text{NaCl}$. A white precipitate of $\\text{BaSO}_4$ shows this is a:',
opts:[['Combination reaction',0],['Double displacement (precipitation) reaction',1],['Simple displacement reaction',0],['Redox reaction only',0]],
rub:'Ions exchange partners and an insoluble salt forms.', expl:'$\\text{Ba}^{2+}$ and $\\text{SO}_4^{2-}$ combine into insoluble $\\text{BaSO}_4$ while $\\text{Na}^+$ and $\\text{Cl}^-$ stay dissolved: ions exchange partners.', tags:['double-displacement','precipitation','seba-pyq'] },
{ code:'Q11', t:'mcq', topic:'redox-reactions', sub:'oxidizing-reducing-agents', d:3, skill:'reasoning', marks:1, neg:0.25, time:75, board:'CBSE', pyq:null,
stem:'In the reaction $\\text{ZnO} + \\text{C} \\rightarrow \\text{Zn} + \\text{CO}$, the oxidising agent is:',
opts:[['$\\text{C}$, it is oxidised',0],['$\\text{ZnO}$, it oxidises carbon',1],['$\\text{Zn}$, it is reduced',0],['$\\text{CO}$, it is the product',0]],
rub:'Oxidising agent is the species that gets reduced.', expl:'$\\text{ZnO}$ loses oxygen (reduced) and oxidises carbon to $\\text{CO}$; hence $\\text{ZnO}$ is the oxidising agent.', tags:['redox','oxidising-agent'] },
{ code:'Q12', t:'mcq', topic:'balancing-equations', sub:'state-symbols', d:1, skill:'recall', marks:1, neg:0.25, time:45, board:'OTHER', pyq:null,
stem:'In the equation $\\text{AgNO}_3(aq) + \\text{NaCl}(aq) \\rightarrow \\text{AgCl}(s) + \\text{NaNO}_3(aq)$, the symbol $(s)$ for $\\text{AgCl}$ indicates:',
opts:[['Silver chloride is dissolved',0],['Silver chloride is a solid precipitate',1],['Reaction needs sunlight',0],['Silver chloride is a gas',0]],
rub:'State symbols show physical states of reactants and products.', expl:'$(aq)$ means aqueous solution and $(s)$ means solid; $\\text{AgCl}$ separates as a white solid precipitate.', tags:['state-symbols','precipitation'] },
];
