// Q13-Q18 assertion-reason (standard 4 codes A-D)
module.exports = [
{ code:'Q13', t:'assertion_reason', topic:'balancing-equations', sub:'hit-and-trial', d:1, skill:'recall', marks:1, neg:0.25, time:60, board:'CBSE', pyq:null,
stem:'Assertion (A): A skeletal equation must be balanced before studying a reaction quantitatively. Reason (R): Mass is conserved, so atoms of each element must be equal on both sides.',
opts:[['Both A and R true, R explains A',1],['Both true, R does not explain A',0],['A true, R false',0],['A false, R true',0]],
rub:'Balancing enforces mass conservation for calculations.', expl:'Balancing equalises atom counts as the conservation law demands; quantitative study needs a balanced equation.', tags:['assertion-reason','balancing'] },
{ code:'Q14', t:'assertion_reason', topic:'types-of-reactions', sub:'displacement-reactions', d:2, skill:'reasoning', marks:1, neg:0.25, time:70, board:'CBSE', pyq:2023,
stem:'Assertion (A): Zinc displaces copper from copper sulphate solution. Reason (R): Zinc is placed below copper in the activity series.',
opts:[['Both true, R explains A',0],['Both true, R does not explain A',0],['A true, R false',1],['A false, R true',0]],
rub:'More reactive metal sits higher in the series.', expl:'Zinc does displace copper, but zinc is ABOVE copper in the series, so R is false.', tags:['assertion-reason','reactivity-series'] },
{ code:'Q15', t:'assertion_reason', topic:'redox-reactions', sub:'oxidizing-reducing-agents', d:2, skill:'application', marks:1, neg:0.25, time:70, board:'CBSE', pyq:null,
stem:'Assertion (A): In the reaction of copper oxide with hydrogen, copper oxide is the oxidising agent. Reason (R): The substance that loses oxygen is reduced and oxidises the other reactant.',
opts:[['Both A and R true, R explains A',1],['Both true, R does not explain A',0],['A true, R false',0],['A false, R true',0]],
rub:'Oxidising agent undergoes reduction itself.', expl:'CuO loses oxygen (reduced) while oxidising hydrogen to water; hence it is the oxidising agent.', tags:['assertion-reason','redox'] },
{ code:'Q16', t:'assertion_reason', topic:'corrosion', sub:'prevention-of-corrosion', d:2, skill:'application', marks:1, neg:0.25, time:60, board:'SEBA', pyq:null,
stem:'Assertion (A): Galvanised iron stays protected even if the zinc coating breaks. Reason (R): Zinc is more reactive than iron and gets oxidised first.',
opts:[['Both A and R true, R explains A',1],['Both true, R does not explain A',0],['A true, R false',0],['A false, R true',0]],
rub:'Sacrificial protection by the more reactive metal.', expl:'Zinc acts as a sacrificial anode: it corrodes preferentially, so iron stays protected at scratches.', tags:['assertion-reason','galvanisation'] },
{ code:'Q17', t:'assertion_reason', topic:'exothermic-endothermic', sub:'thermal-decomposition-heat', d:2, skill:'reasoning', marks:1, neg:0.25, time:70, board:'CBSE', pyq:null,
stem:'Assertion (A): Decomposition of calcium carbonate requires heating. Reason (R): All decomposition reactions are exothermic and release heat.',
opts:[['Both true, R explains A',0],['Both true, R does not explain A',0],['A true, R false',1],['A false, R true',0]],
rub:'Thermal decomposition absorbs heat; it is endothermic.', expl:'Calcium carbonate decomposition needs continuous heating because it absorbs energy; R is false.', tags:['assertion-reason','endothermic'] },
{ code:'Q18', t:'assertion_reason', topic:'rancidity', sub:'prevention-rancidity', d:1, skill:'recall', marks:1, neg:0.25, time:60, board:'CBSE', pyq:null,
stem:'Assertion (A): Adding antioxidants to oily foods slows rancidity. Reason (R): Antioxidants prevent oxidation of fats and oils.',
opts:[['Both A and R true, R explains A',1],['Both true, R does not explain A',0],['A true, R false',0],['A false, R true',0]],
rub:'Antioxidants block free-radical oxidation chains.', expl:'Antioxidants are oxidised instead of the food fats, breaking the oxidation chain that causes rancidity.', tags:['assertion-reason','rancidity'] },
];
