// Q32-Q38 fill_blank + equation
module.exports = [
{ code:'Q32', t:'mcq', topic:'corrosion', sub:'prevention-of-corrosion', d:1, skill:'recall', marks:1, neg:0.25, time:45, board:'CBSE', pyq:null, parent:'Q30',
stem:'(Case Q30) Painting or oiling prevents rusting mainly by:',
opts:[['Making iron harder',0],['Cutting contact with air and moisture',1],['Adding carbon to iron',0],['Heating the surface',0]],
rub:'Barrier methods block air and water.', expl:'Paint/oil films keep oxygen and moisture away from the iron surface.', tags:['case-child','prevention'] },
{ code:'Q33', t:'short', topic:'corrosion', sub:'rusting-of-iron', d:2, skill:'application', marks:2, neg:0, time:120, board:'CBSE', pyq:null, parent:'Q30',
stem:'(Case Q30) Write the condition for rusting and give the formula of rust. Suggest one prevention method.',
opts:[], ans:{ text:['both air and moisture','Fe2O3.xH2O','painting/oiling/galvanising'] },
rub:'1 mark conditions + 1 mark formula/method.', expl:'Rusting needs air and moisture; rust is hydrated ferric oxide Fe2O3.xH2O; prevent by painting, oiling, greasing, or galvanisation.', tags:['case-child','short'] },
{ code:'Q34', t:'fill_blank', topic:'types-of-reactions', sub:'combination-reactions', d:1, skill:'recall', marks:1, neg:0, time:45, board:'CBSE', pyq:null,
stem:'Fill in the blank: Burning of coal (C+O2->CO2) is a ______ reaction and releases heat, so it is also ______.',
opts:[], ans:{ blanks:['combination','exothermic'] },
rub:'Accept synonyms: synthesis; heat-releasing.', expl:'Two reactants form one product (combination/synthesis) and heat is released (exothermic).', tags:['fill-blank','combination'] },
{ code:'Q35', t:'fill_blank', topic:'balancing-equations', sub:'hit-and-trial', d:2, skill:'application', marks:1, neg:0, time:60, board:'CBSE', pyq:null,
stem:'Balance: Fe+H2O->Fe3O4+H2. Coefficients in order are ___, ___, ___, ___.',
opts:[], ans:{ blanks:['3','4','1','4'] },
rub:'Exact coefficients 3, 4, 1, 4.', expl:'3Fe+4H2O->Fe3O4+4H2 balances Fe (3), H (8), O (4) on each side.', tags:['fill-blank','balancing'] },
{ code:'Q36', t:'fill_blank', topic:'redox-reactions', sub:'oxidation-reduction-defs', d:2, skill:'application', marks:1, neg:0, time:60, board:'SEBA', pyq:null,
stem:'In CuO+H2->Cu+H2O, CuO is ______ (oxidised/reduced) and acts as the ______ agent.',
opts:[], ans:{ blanks:['reduced','oxidising'] },
rub:'Loses oxygen = reduced; oxidises other = oxidising agent.', expl:'CuO loses oxygen so it is reduced; it oxidises hydrogen, hence the oxidising agent.', tags:['fill-blank','redox'] },
{ code:'Q37', t:'fill_blank', topic:'rancidity', sub:'prevention-rancidity', d:1, skill:'recall', marks:1, neg:0, time:45, board:'CBSE', pyq:null,
stem:'Rancidity is prevented by adding ______ and by flushing packets with ______ gas.',
opts:[], ans:{ blanks:['antioxidants','nitrogen'] },
rub:'Accept anti-oxidant; inert gas nitrogen.', expl:'Antioxidants stop oxidation chains; nitrogen displaces oxygen in food packets.', tags:['fill-blank','rancidity'] },
{ code:'Q38', t:'equation', topic:'balancing-equations', sub:'hit-and-trial', d:2, skill:'application', marks:2, neg:0, time:120, board:'CBSE', pyq:2021,
stem:'Write the balanced equation for: zinc reacts with dilute sulphuric acid to form zinc sulphate and hydrogen gas.',
opts:[], ans:{ equations:['Zn+H2SO4->ZnSO4+H2'] },
rub:'Correct formulae (1) + balanced (1).', expl:'Zn+H2SO4->ZnSO4+H2 is already balanced: 1 Zn, 2 H, 1 S, 4 O each side.', tags:['equation','balancing'] },
];
