// Q39-Q44 equation + short
module.exports = [
{ code:'Q39', t:'equation', topic:'balancing-equations', sub:'hit-and-trial', d:3, skill:'application', marks:3, neg:0, time:150, board:'CBSE', pyq:null,
stem:'Balance: Fe2O3+CO->Fe+CO2 (blast-furnace style reduction). Give the balanced equation.',
opts:[], ans:{ equations:['Fe2O3+3CO->2Fe+3CO2'] },
rub:'Formulae (1) + atom balance (2).', expl:'Fe2O3+3CO->2Fe+3CO2: 2 Fe, 3 C, 6 O each side.', tags:['equation','balancing'] },
{ code:'Q40', t:'equation', topic:'types-of-reactions', sub:'double-displacement', d:2, skill:'application', marks:2, neg:0, time:120, board:'SEBA', pyq:null,
stem:'Write the balanced equation for lead nitrate with potassium iodide (yellow precipitate).',
opts:[], ans:{ equations:['Pb(NO3)2+2KI->PbI2+2KNO3'] },
rub:'Correct formulae (1) + balanced (1).', expl:'Pb(NO3)2+2KI->PbI2+2KNO3 balances Pb, N, O, K, I.', tags:['equation','precipitation'] },
{ code:'Q41', t:'equation', topic:'balancing-equations', sub:'state-symbols', d:2, skill:'application', marks:2, neg:0, time:120, board:'CBSE', pyq:null,
stem:'Write the balanced equation with state symbols: silver nitrate solution + sodium chloride solution -> silver chloride + sodium nitrate solution.',
opts:[], ans:{ equations:['AgNO3(aq)+NaCl(aq)->AgCl(s)+NaNO3(aq)'] },
rub:'Balanced (1) + state symbols (1).', expl:'AgNO3(aq)+NaCl(aq)->AgCl(s)+NaNO3(aq): atoms balance and states are shown.', tags:['equation','state-symbols'] },
{ code:'Q42', t:'short', topic:'types-of-reactions', sub:'displacement-reactions', d:2, skill:'application', marks:2, neg:0, time:120, board:'CBSE', pyq:null,
stem:'Why does an iron nail dipped in copper sulphate solution turn brownish, while the blue colour fades? Write the equation.',
opts:[], ans:{ text:['iron more reactive displaces copper','Fe+CuSO4->FeSO4+Cu'] },
rub:'Explanation (1) + equation (1).', expl:'Fe is more reactive than Cu, so Fe+CuSO4->FeSO4+Cu; copper coats the nail (brown) and blue Cu2+ leaves solution.', tags:['short','displacement'] },
{ code:'Q43', t:'short', topic:'balancing-equations', sub:'hit-and-trial', d:2, skill:'application', marks:3, neg:0, time:150, board:'CBSE', pyq:null,
stem:'Translate and balance: magnesium + oxygen -> magnesium oxide. Explain the hit-and-trial steps.',
opts:[], ans:{ text:['2Mg+O2->2MgO','balance Mg then O or count atoms'] },
rub:'Equation (2) + method (1).', expl:'Skeletal: Mg+O2->MgO. Balance O by 2MgO, then Mg by 2Mg: 2Mg+O2->2MgO.', tags:['short','balancing'] },
{ code:'Q44', t:'short', topic:'exothermic-endothermic', sub:'respiration-combustion', d:1, skill:'recall', marks:2, neg:0, time:120, board:'CBSE', pyq:null,
stem:'Why is respiration considered an exothermic reaction? Write the word equation for glucose breakdown.',
opts:[], ans:{ text:['energy released','glucose+oxygen->carbon dioxide+water+energy'] },
rub:'Exothermic reason (1) + equation (1).', expl:'C6H12O6+6O2->6CO2+6H2O+energy releases heat; body temperature is maintained by this energy.', tags:['short','respiration'] },
];
