// Q45-Q50 short + long + extras
module.exports = [
{ code:'Q45', t:'short', topic:'corrosion', sub:'prevention-of-corrosion', d:2, skill:'application', marks:3, neg:0, time:150, board:'CBSE', pyq:2020,
stem:'What is corrosion? State two ways to prevent rusting of iron and explain how galvanisation protects even scratched surfaces.',
opts:[], ans:{ text:['slow eating of metals by air moisture','painting oiling galvanising','zinc sacrificial'] },
rub:'Definition (1) + methods (1) + galvanisation (1).', expl:'Corrosion eats metals by air/moisture attack; prevent by painting, oiling, galvanisation. Zinc is more reactive and corrodes first.', tags:['short','corrosion'] },
{ code:'Q46', t:'short', topic:'rancidity', sub:'causes-of-rancidity', d:1, skill:'recall', marks:2, neg:0, time:120, board:'CBSE', pyq:null,
stem:'What is rancidity? Mention two methods used to prevent it in packaged foods.',
opts:[], ans:{ text:['oxidation of fats oils bad smell taste','antioxidants nitrogen flushing airtight'] },
rub:'Definition (1) + two methods (1).', expl:'Fats/oils oxidise giving foul smell/taste; add antioxidants, flush nitrogen, store airtight, refrigerate.', tags:['short','rancidity'] },
{ code:'Q47', t:'long', topic:'types-of-reactions', sub:'decomposition-reactions', d:3, skill:'reasoning', marks:5, neg:0, time:300, board:'CBSE', pyq:null,
stem:'Describe three types of decomposition reactions (thermal, electrolytic, photolytic) with one balanced equation each.',
opts:[], ans:{ text:['CaCO3->CaO+CO2 heat','2H2O->2H2+O2 electricity','2AgCl->2Ag+Cl2 sunlight'] },
rub:'Each type with equation: 1+1+1 plus explanation 2.', expl:'Thermal: CaCO3->CaO+CO2; electrolytic: 2H2O->2H2+O2; photolytic: 2AgCl->2Ag+Cl2. One reactant splits using heat, current, or light.', tags:['long','decomposition'] },
{ code:'Q48', t:'long', topic:'redox-reactions', sub:'electronic-concept', d:3, skill:'reasoning', marks:5, neg:0, time:300, board:'CBSE', pyq:null,
stem:'Define oxidation and reduction in terms of oxygen transfer and electron transfer. Illustrate with CuO+H2->Cu+H2O and identify oxidising/reducing agents.',
opts:[], ans:{ text:['gain loss of oxygen','loss gain of electrons','CuO oxidising agent H2 reducing agent'] },
rub:'Definitions (2) + example (2) + agents (1).', expl:'Oxidation: gain O / lose e-; reduction: lose O / gain e-. Here H2 oxidised, CuO reduced; CuO is oxidising agent, H2 is reducing agent.', tags:['long','redox'] },
{ code:'Q49', t:'mcq', topic:'balancing-equations', sub:'hit-and-trial', d:2, skill:'application', marks:1, neg:0.25, time:60, board:'CBSE', pyq:2023,
stem:'Which equation is balanced? (a) N2+H2->NH3 (b) N2+3H2->2NH3 (c) 2N2+3H2->2NH3',
opts:[['Only (a)',0],['Only (b)',1],['Only (c)',0],['All three',0]],
rub:'Check N and H counts.', expl:'(b) N2+3H2->2NH3 has 2 N and 6 H each side; others do not balance.', tags:['mcq','balancing'] },
{ code:'Q50', t:'mcq', topic:'exothermic-endothermic', sub:'respiration-combustion', d:1, skill:'recall', marks:1, neg:0, time:40, board:'SEBA', pyq:null,
stem:'Decomposition of vegetable matter into compost is:',
opts:[['Endothermic',0],['Exothermic',1],['Photolytic only',0],['Neither',0]],
rub:'Decay releases heat.', expl:'Decomposition of organic matter releases heat to surroundings, so it is exothermic.', tags:['mcq','exothermic'] },
];
