// Q51-Q62 booster: full type x difficulty coverage, SEBA co-presence, PYQ spread.
module.exports = [
{ code:'Q51', t:'mcq', topic:'balancing-equations', sub:'word-equations', d:1, skill:'recall', marks:1, neg:0.25, time:45, board:'SEBA', pyq:2018,
stem:'The word equation hydrogen+oxygen->water corresponds to the balanced equation:',
opts:[['H2+O2->H2O',0],['2H2+O2->2H2O',1],['H2+2O2->H2O',0],['2H2+2O2->H2O',0]],
rub:'4 H and 2 O each side.', expl:'2H2+O2->2H2O balances H (4) and O (2).', tags:['mcq','word-equation','seba-pyq'] },
{ code:'Q52', t:'mcq', topic:'rancidity', sub:'causes-of-rancidity', d:1, skill:'recall', marks:1, neg:0.25, time:40, board:'SEBA', pyq:2022,
stem:'Rancidity in fatty foods is caused by:',
opts:[['Reduction of oils',0],['Oxidation of fats and oils',1],['Fermentation by yeast',0],['Freezing of water',0]],
rub:'Oxygen attacks unsaturated fats.', expl:'Air oxidises fats/oils, producing foul smell and taste.', tags:['mcq','rancidity','seba-pyq'] },
{ code:'Q53', t:'mcq', topic:'types-of-reactions', sub:'combination-reactions', d:2, skill:'application', marks:1, neg:0.25, time:55, board:'CBSE', pyq:2024,
stem:'Which pair both undergo combination reactions? (a) C+O2 (b) CaCO3 on heating (c) H2+Cl2 in light (d) Zn+CuSO4.',
opts:[['(a) and (c)',1],['(b) and (d)',0],['(a) and (b)',0],['(c) and (d)',0]],
rub:'Two reactants form one product.', expl:'C+O2->CO2 and H2+Cl2->2HCl are combinations; heating CaCO3 is decomposition; Zn+CuSO4 is displacement.', tags:['mcq','combination'] },
{ code:'Q54', t:'assertion_reason', topic:'types-of-reactions', sub:'combination-reactions', d:1, skill:'recall', marks:1, neg:0.25, time:60, board:'SEBA', pyq:null,
stem:'A: Burning magnesium ribbon in air is a combination reaction. R: Two reactants combine to form a single product MgO.',
opts:[['Both true, R explains A',1],['Both true, unrelated',0],['A true, R false',0],['A false, R true',0]],
rub:'2Mg+O2->2MgO is combination.', expl:'Magnesium and oxygen combine into one product, magnesium oxide.', tags:['assertion-reason','combination'] },
{ code:'Q55', t:'statement', topic:'redox-reactions', sub:'oxidation-reduction-defs', d:3, skill:'reasoning', marks:1, neg:0.25, time:80, board:'CBSE', pyq:null,
stem:'Statement I: Oxidation is loss of electrons. Statement II: In Zn+CuSO4->ZnSO4+Cu, zinc is oxidised. Choose:',
opts:[['Both true; II follows the electronic concept',1],['Both true, unrelated',0],['I true, II false',0],['I false, II true',0]],
rub:'Zn->Zn2+ + 2e- is oxidation.', expl:'Zinc loses electrons (oxidised); copper ions gain them (reduced).', tags:['statement','redox'] },
{ code:'Q56', t:'fill_blank', topic:'exothermic-endothermic', sub:'thermal-decomposition-heat', d:2, skill:'application', marks:1, neg:0, time:60, board:'CBSE', pyq:null,
stem:'CaCO3->CaO+CO2 needs heating, so it is ______; respiration releases energy, so it is ______.',
opts:[], ans:{ blanks:['endothermic','exothermic'] },
rub:'Heat absorbed vs released.', expl:'Thermal decomposition absorbs heat (endothermic); respiration releases heat (exothermic).', tags:['fill-blank','energy'] },
{ code:'Q57', t:'equation', topic:'exothermic-endothermic', sub:'respiration-combustion', d:1, skill:'recall', marks:2, neg:0, time:120, board:'CBSE', pyq:null,
stem:'Write the balanced equation for combustion of methane (natural gas).',
opts:[], ans:{ equations:['CH4+2O2->CO2+2H2O'] },
rub:'Formulae (1) + balanced (1).', expl:'CH4+2O2->CO2+2H2O balances C, H, O and releases heat.', tags:['equation','combustion'] },
{ code:'Q58', t:'short', topic:'types-of-reactions', sub:'double-displacement', d:3, skill:'reasoning', marks:3, neg:0, time:150, board:'SEBA', pyq:2023,
stem:'Distinguish displacement from double displacement with one example each (with equations).',
opts:[], ans:{ text:['single ion replaced Fe+CuSO4','ions exchanged AgNO3+NaCl'] },
rub:'Definition (1) + two equations (2).', expl:'Displacement: Fe+CuSO4->FeSO4+Cu. Double displacement: AgNO3+NaCl->AgCl+NaNO3.', tags:['short','comparison'] },
{ code:'Q59', t:'long', topic:'balancing-equations', sub:'hit-and-trial', d:3, skill:'reasoning', marks:5, neg:0, time:300, board:'CBSE', pyq:null,
stem:'State the law of conservation of mass. Explain hit-and-trial balancing using H2+O2->H2O and N2+H2->NH3.',
opts:[], ans:{ text:['mass neither created nor destroyed','2H2+O2->2H2O','N2+3H2->2NH3'] },
rub:'Law (1) + method (1) + two equations (3).', expl:'Mass is conserved; balance largest molecules first, then H/O. Results: 2H2+O2->2H2O and N2+3H2->2NH3.', tags:['long','balancing'] },
{ code:'Q60', t:'mcq', topic:'corrosion', sub:'prevention-of-corrosion', d:2, skill:'application', marks:1, neg:0.25, time:55, board:'CBSE', pyq:2024,
stem:'Which stops corrosion by sacrificial protection even when scratched?',
opts:[['Painting',0],['Oiling',0],['Galvanisation (zinc coating)',1],['Polishing',0]],
rub:'Zinc corrodes before iron.', expl:'Zinc is more reactive, so it oxidises preferentially and iron stays protected.', tags:['mcq','galvanisation'] },
{ code:'Q61', t:'equation', topic:'balancing-equations', sub:'hit-and-trial', d:2, skill:'application', marks:2, neg:0, time:120, board:'SEBA', pyq:2019,
stem:'Balance: BaCl2+Na2SO4->BaSO4+NaCl.',
opts:[], ans:{ equations:['BaCl2+Na2SO4->BaSO4+2NaCl'] },
rub:'Na and Cl doubled on RHS.', expl:'BaCl2+Na2SO4->BaSO4+2NaCl balances Ba, Cl, Na, S, O.', tags:['equation','balancing'] },
{ code:'Q62', t:'short', topic:'redox-reactions', sub:'oxidizing-reducing-agents', d:2, skill:'application', marks:2, neg:0, time:120, board:'SEBA', pyq:null,
stem:'In MnO2+4HCl->MnCl2+Cl2+2H2O identify oxidising and reducing agents with one-line reasons.',
opts:[], ans:{ text:['MnO2 oxidising agent reduced','HCl reducing agent oxidised'] },
rub:'Each agent with reason (1+1).', expl:'MnO2 is reduced to MnCl2 (oxidising agent); HCl is oxidised to Cl2 (reducing agent).', tags:['short','redox'] },
];
